import React from "react";

function Header() {
  return (
    <>
      <div className="mt-2 py-4 px-10 flex justify-around">
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            className="size-8"
            src="https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg"
            alt=""
          />
        </div>
      </div>
    </>
  );
}

export default Header;
